In [1]:
# Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

# Logistic Regression
# SVM
# Decision Tree
# Random Forest

In [36]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree
from sklearn.datasets import load_iris
iris=load_iris()

In [4]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(iris.data,iris.target,test_size=0.2)

In [7]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
def get_score(model,X_train,X_test,Y_train,Y_test):
    model.fit(X_train,Y_train)
    return model.score(X_test,Y_test)

In [11]:
get_score(LinearRegression(),X_train,X_test,Y_train,Y_test)

0.944937167479968

In [12]:
get_score(SVC(),X_train,X_test,Y_train,Y_test)

0.9666666666666667

In [13]:
get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test)

0.9666666666666667

In [17]:
get_score(tree.DecisionTreeClassifier(),X_train,X_test,Y_train,Y_test)

0.9333333333333333

In [18]:
#cross_val funcrion
from sklearn.model_selection import cross_val_score

In [23]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data,iris.target,cv=3)

array([0.96, 0.96, 0.94])

In [24]:
cross_val_score(SVC(gamma='auto'),iris.data,iris.target,cv=3)

array([0.98, 0.98, 0.96])

In [35]:
cross_val_score(RandomForestClassifier(n_estimators=60),iris.data,iris.target,cv=3)

array([0.98, 0.94, 0.98])

In [26]:
cross_val_score(tree.DecisionTreeClassifier(),iris.data,iris.target,cv=3)

array([0.98, 0.92, 1.  ])

In [39]:
#average score for random forest 
np.average(cross_val_score(RandomForestClassifier(n_estimators=60),iris.data,iris.target,cv=3))

0.9666666666666667